lib/timesheets_web/router.ex
defmodule TimesheetsWeb.Router do
  use TimesheetsWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug TimesheetsWeb.Plugs.FetchCurrentUser
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TimesheetsWeb do
    pipe_through :browser

    get "/", PageController, :index

    resources "/managers", ManagerController

    resources "/users", UserController,
      only: [:create, :show, :delete, :index, :new]

    resources "/sessions", SessionController, 
      only: [:new, :create, :delete], singleton: true 
  end

  # Other scopes may use custom stacks.
  # scope "/api", TimesheetsWeb do
  #   pipe_through :api
  # end
end

lib/timesheets_web/views/layout_view.ex
defmodule TimesheetsWeb.LayoutView do
  use TimesheetsWeb, :view

  def nav_link(conn, text, path) do
    curr_path = "/" <> Enum.join(conn.path_info, "/")
    active = if curr_path == path do "active" else "" end
    raw ~s(
      <li class="nav-item #{active}">
        <a class="nav-link" href="#{path}">#{text}</a>
      </li>
    )
  end
end

lib/timesheets_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Timesheets · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script>
     window.csrf_token = "<%= Phoenix.Controller.get_csrf_token() %>";
    </script>
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        <div class="col-4">
          <span class="navbar-brand">Timesheets</span>
        </div>
        <div class="col-4">
          <ul class="navbar-nav mr-auto">
            <%= nav_link(@conn, "Home", Routes.page_path(@conn, :index)) %>
            <%= if @current_user do %>
            <%= nav_link(@conn, "Users", Routes.user_path(@conn, :index)) %>
	    <% end %>
          </ul>
        </div>
        <div class="col-4 text-light">
          <%= if @current_user do %>
            User: <%= link(@current_user.name,
              to: Routes.user_path(@conn, :show, @current_user)) %>
            (<%= link("Logout", to: Routes.session_path(@conn, :delete),
              method: :delete) %>)
          <% else %>
            <%= link("Login", to: Routes.session_path(@conn, :new)) %> |
            <%= link("Register", to: Routes.user_path(@conn, :new)) %>
          <% end %>
        </div>
      </nav>
      <div>
        <%= if get_flash(@conn, :info) do %>
          <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
        <% end %>
        <%= if get_flash(@conn, :error) do %>
          <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
        <% end %>
        <%= render @view_module, @view_template, assigns %>
      </div>
    </div>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>